# code: language=ansible
---
- name: Criar repositório {{ item.name }}
  uri:
    url: "https://dev-nexus.desenv.com/service/rest/v1/repositories/npm/proxy"
    method: POST
    validate_certs: false
    use_netrc: true
    status_code:
      - 201
    headers:
      accept: "application/json"
      Content-Type: "application/json"
      NX-ANTI-CSRF-TOKEN: "0.7944781578949698"
      X-Nexus-UI: "true"
    body_format: json
    body:

  ignore_errors: true
  tags:
    - repositories
    - npm-proxy
