- name: Baixar repositorio infra-devops
  become: true
  gather_facts: false
  vars:
     host: all
     git_user: user
     git_pass: passwd
  hosts: "{{ host }}"
  environment:
    no_proxy: .desenv.com,.banpara.com
    GIT_SSL_CAINFO: /etc/ssl/certs/banparaca.pem
  tasks:
  - name: Criar arquivo banparaca.pem
    copy:
      content: |
        -----BEGIN CERTIFICATE-----
        MIIDrTCCApWgAwIBAgIQXVEG+vzwlIVPNtZphBQHKTANBgkqhkiG9w0BAQsFADBK
        MRMwEQYKCZImiZPyLGQBGRYDY29tMRcwFQYKCZImiZPyLGQBGRYHYmFucGFyYTEa
        MBgGA1UEAxMRY2VydGlzaWduLWJhbnBhcmEwHhcNMjEwNDE5MjM1NjQxWhcNMjYw
        NDIwMDAwNjQwWjBKMRMwEQYKCZImiZPyLGQBGRYDY29tMRcwFQYKCZImiZPyLGQB
        GRYHYmFucGFyYTEaMBgGA1UEAxMRY2VydGlzaWduLWJhbnBhcmEwggEiMA0GCSqG
        SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCVgsP2qOeuIbBAwHBnNJoek9cujGV0qtKm
        7A0gHrTYYqtGL8wJVpB8cB4Cpk2U9Yu5ePkfpOBQLuw5sm/jFTChimZFEFSL6R5s
        LbZ13/M1FnpfVss56mE0+SKCRcPU2XaYnDltieHIb17Yn25R16UuiLm808+PUXqM
        8yAN9oIqg4Tyf/TaiuObii3NSnhMafTLZPY288caBFnmo0mAvxoy17qTidp5KMVe
        CXJ5uFrzOAZ9UGLimGfHQKJBv0rnkvoxUb3SXfeHAuQL+iLVKfsX4Av0jxf4/7xl
        qzOonObCvXok0a5YqioyVq75SO38afC7rGOFW5EPsEC95uhEJIeBAgMBAAGjgY4w
        gYswEwYJKwYBBAGCNxQCBAYeBABDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQF
        MAMBAf8wHQYDVR0OBBYEFC17Qr0D2y0mnGWjIOm0mjx5j53tMBIGCSsGAQQBgjcV
        AQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYEFJjXsltHZl1mqSnW9CV0X6nj5k6UMA0G
        CSqGSIb3DQEBCwUAA4IBAQBxl/kT4ksHeQzTHkTCuYlxxmtwQC+1KZ9JCWkPjg/s
        aaxNhUOkVs2Lrq+ACvqCxr+ZGQvanVWB0rZWE7ZB7S4hng0BSCL5O+FfeCZNfpq2
        1Widx6qU7IIjyqf+8seC+Zl4cfrkn9uc/pHI5Wq4nOYdXJZt3Aw3hjOGVxVU6tCZ
        BJlG7KfWnaq2HtNkPZ9iOoRi1vrzaCuzLW0J68Tj0AO1NWqyofnYw1sDVfE+VDO/
        RkmBQSzmVYCEdJVNKZJlgtuM6T1ZgU1OlwOc5+pmWQ+jc8k5R6bAAPMTXeym1STZ
        uJX1Ekpb9HMUF03Y8/EKFMVDdxK/g4JyP51CnTybC+cK
        -----END CERTIFICATE-----
      dest: /etc/ssl/certs/banparaca.pem
      mode: 0644
  - name: Instalar Git
    ansible.builtin.dnf:
      name: git
      state: present
  - name: Clonar repositório do GitLab
    git:
      repo: https://{{ git_user }}:{{ git_pass }}@gitlab.banpara.com/recursos/devops-banpara/infra-devops
      dest: /tmp/infra-devops
      version: nexus
  - name: Adicionar configuração CURL_CA_BUNDLE ao arquivo /etc/environment
    lineinfile:
      dest: /etc/environment
      line: 'GIT_SSL_CAINFO=/etc/ssl/certs/banparaca.pem'
      state: present

