# code: language=ansible
- name: Configurar Nexus
  become: true
  gather_facts: false
  vars:
     host: all
     update: false
  hosts: "{{ host }}"
  tasks:
    - name: Criar blobstores
      include_tasks: tasks/nexus-create-blobstore-task.yaml
      vars:
        nexus_blobstores:
         - url: "/opt/nexusdata/nexus3/blobs/release/raw-release"
         - url: "/opt/nexusdata/nexus3/blobs/snapshot/raw-snapshot"
         - url: "/opt/nexusdata/nexus3/blobs/snapshot/npm-snapshot"
         - url: "/opt/nexusdata/nexus3/blobs/release/npm-release"
         - url: "/opt/nexusdata/nexus3/blobs/release/nuget-release"
         - url: "/opt/nexusdata/nexus3/blobs/snapshot/nuget-snapshot"
         - url: "/opt/nexusdata/nexus3/blobs/snapshot/maven2-snapshot"
         - url: "/opt/nexusdata/nexus3/blobs/release/maven2-release"
         - url: "/opt/nexusdata/nexus3/blobs/release/helm-release"
         - url: "/opt/nexusdata/nexus3/blobs/snapshot/helm-snapshot"
         - url: "/opt/nexusdata/nexus3/blobs/container/registry-banpara"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-jasperreports"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/npm-proxy-npmjs"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-primefaces"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/nuget-proxy-org"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/nuget-proxy-api"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/nuget-proxy-vibe-v2"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/nuget-proxy-vibe-v3"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-jboss"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-flutter-infra"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-apache"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/npm-proxy-fontawesome"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-redhat"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/npm-proxy-yarnpkg"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-central"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-pdcase"
         - url: "/opt/nexusdata/nexus3/blobs/proxy/maven2-proxy-flutter-pub-dev"
         - url: "/opt/nexusdata/nexus3/blobs/release/maven2-group"
         - url: "/opt/nexusdata/nexus3/blobs/release/nuget-group"
         - url: "/opt/nexusdata/nexus3/blobs/release/npm-group"
         - url: "/opt/nexusdata/nexus3/blobs/release/raw-group"
      loop: "{{ nexus_blobstores }}"
      tags:
        - blobstores
    - name: Criar repositórios raw hosted
      include_tasks: tasks/nexus-create-raw-hosted-repo-task.yaml
      vars:
        nexus_repositories:
          - name: "raw-release"
          - name: "raw-snapshot"
      loop: "{{ nexus_repositories }}"
      tags:
        - repositories
        - raw-hosted
    - name: Criar repositórios maven2 hosted
      include_tasks: tasks/nexus-create-maven-hosted-repo-task.yaml
      vars:
        nexus_repositories:
          - name: "maven-release"
          - name: "maven-snapshot"
      loop: "{{ nexus_repositories }}"
      tags:
        - repositories
        - maven-hosted
    - name: Criar repositórios nuget hosted
      include_tasks: tasks/nexus-create-nuget-hosted-repo-task.yaml
      vars:
        nexus_repositories:
          - name: "nuget-release"
          - name: "nuget-snapshot"
      loop: "{{ nexus_repositories }}"
      tags:
        - repositories
        - nuget-hosted
    - name: Criar repositórios helm hosted
      include_tasks: tasks/nexus-create-helm-hosted-repo-task.yaml
      vars:
        nexus_repositories:
          - name: "helm-release"
          - name: "helm-snapshot"
      loop: "{{ nexus_repositories }}"
      tags:
        - repositories
        - helm-hosted
    - name: Criar repositórios npm hosted
      include_tasks: tasks/nexus-create-npm-hosted-repo-task.yaml
      vars:
        nexus_repositories:
          - name: "npm-release"
          - name: "npm-snapshot"
      loop: "{{ nexus_repositories }}"
      tags:
        - repositories
        - npm-hosted
    - name: Criar repositórios docker hosted
      include_tasks: tasks/nexus-create-docker-hosted-repo-task.yaml
      vars:
        nexus_repositories:
          - name: "registry-openshift"
      loop: "{{ nexus_repositories }}"
      tags:
        - repositories
        - docker-hosted
    - name: Criar repositórios maven proxy 
      include_tasks: tasks/nexus-create-maven-proxy-repo-task.yaml
      vars:
        nexus_repositories:
          - name: "maven2-proxy-central"
            url: "https://repo1.maven.org/maven2/"
          - name: "maven2-proxy-apache"
            url: "https://repo.maven.apache.org/maven2/"
          - name: "maven2-proxy-redhat"
            url: "https://maven.repository.redhat.com/ga/"
          - name: "maven2-proxy-flutter-pub-dev"
            url: "https://pub.dev/api/packages/test/"
          - name: "maven2-proxy-jasperreports"
            url: "https://jaspersoft.jfrog.io/ui/native/jaspersoft-repo"
          - name: "maven2-proxy-primefaces"
            url: "http://repository.primefaces.org"
          - name: "maven2-proxy-flutter-infra"
            url: "https://storage.googleapis.com/flutter_infra/releases"
          - name: "maven2-proxy-pdcase"
            url: "https://www.pdcase.com/nexus/"
          - name: "maven2-proxy-jboss"
            url: "https://repository.jboss.org/nexus/content/groups/public/"
      loop: "{{ nexus_repositories}}"
      tags:
        - repositories
        - maven-proxy
