- name: Configuração de backup do nexus
  become: true  
  gather_facts: false
  vars:
     host: all
     restore: false
     nfs_user: user
     nfs_pass: pass
  hosts: "{{ host }}"
  environment:
    http_proxy: http://servicelinux:Ab123456@10.0.1.186:8080/
    https_proxy: http://servicelinux:Ab123456@10.0.1.186:8080/
  tasks:
  - name: Instalar cifs-utils usando dnf
    ansible.builtin.dnf:
      name: cifs-utils
      state: present
  - name: Copiar arquivos para diretórios específicos
    ansible.builtin.copy:
      src: "/tmp/infra-devops/nexus/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: nexus
      group: nexus
      mode: "{{ item.mode | default('0644') }}"
      remote_src: true
    loop:
      - { src: 'nexus_backup.sh', dest: '/opt/script/nexus_backup.sh' }
      - { src: 'nexus_log_clean.sh', dest: '/opt/script/nexus_log_clean.sh' }
  - name: Adicionar entrada de cron para backup
    ansible.builtin.cron:
      name: "Backup Nexus"
      minute: 0
      hour: 18
      weekday: 5
      job: "/opt/script/nexus_backup.sh > /tmp/backup.log 2>&1"
  - name: Adicionar entrada de cron para limpeza de logs
    ansible.builtin.cron:
      name: "Limpeza de Logs Nexus"
      minute: 0
      hour: 18
      job: "/opt/script/nexus_log_clean.sh > /tmp/cleanfiles.log 2>&1"
  - name: Criar arquivo /etc/nfs-credentials
    copy:
      content: |
        username={{ nfs_user }}
        password={{ nfs_pass }}
      dest: /etc/nfs-credentialsss
      mode: 0644
  - name: Adicionar ponto de montagem ao /etc/fstab
    lineinfile:
      path: /etc/fstab
      line: "//fileserver.banpara.com/publica/BackupDevops/nexus /mnt/win_share cifs rw,credentials=/etc/nfs-credentials 0 0"
      insertafter: EOF 
